### ISSUE TITLE
Integration with Hosted Dynamics?

### ISSUE THREAD

**Issue by ch0use** [identitypt/confluence-dynamics-crm-plugin#1]
Is there any support for using this plugin with a Hosted Dynamics CRM environment?

**Comment by ricardojcarvalho** [comment]
Hi ch0use.

I don't have any experience with Hosted Dynamics CRM, are you able to modify the HTTP Response Headers as mentioned in this project's wiki? If so, the plugin should work in the same way as any other DCRM instance.

**Comment by ch0use** [comment]
Sorry, just saw this. I did ask and it sounds like we are not able to modify the HTTP Response Headers.
