### ISSUE TITLE
After account, why not opportunities or other entities? And more...

### ISSUE THREAD

**Issue by pzitoun** [identitypt/confluence-dynamics-crm-plugin#2]
Nice to have this macro and get data from Microsoft CRM but this seems to be limited to Accounts. We use (and all CRM) are mainly centered around opportunities. We would like to create an opportunity review from Confluence.
In the future, update CRM from Confluence will be F A N T A S T I C.

**Comment by ricardojcarvalho** [comment]
Hi pzitoun 

We initially developed this plugin for a specific use case, and decided to publish it afterwards. We're hoping to add more features as we get feedback from users. Thanks for trying the plugin and getting back to us.

Best regards.
